-- ClarityPath 64卦数据库初始化脚本
-- 成功学+心理学风格，面向欧美市场

CREATE TABLE IF NOT EXISTS hexagrams_64 (
    id INTEGER PRIMARY KEY,
    sequence_number INTEGER UNIQUE,  -- 传统卦序 1-64
    name_cn TEXT NOT NULL,
    name_en TEXT NOT NULL,
    upper_trigram TEXT NOT NULL,     -- 上卦
    lower_trigram TEXT NOT NULL,     -- 下卦
    core_theme TEXT NOT NULL,        -- 核心主题
    energy_state TEXT NOT NULL,      -- 能量状态描述
    action_1 TEXT NOT NULL,          -- 行动建议1
    action_2 TEXT NOT NULL,          -- 行动建议2
    action_3 TEXT NOT NULL,          -- 行动建议3
    timing_advice TEXT NOT NULL CHECK (timing_advice IN ('NOW', 'WAIT', 'ADJUST')),
    risk_warning TEXT NOT NULL,      -- 风险提示
    category TEXT                    -- 分类标签
);

-- 清空现有数据（如果需要重新初始化）
-- DELETE FROM hexagrams_64;

-- 插入64卦数据
INSERT INTO hexagrams_64 (id, sequence_number, name_cn, name_en, upper_trigram, lower_trigram, core_theme, energy_state, action_1, action_2, action_3, timing_advice, risk_warning, category) VALUES
-- 上卦为乾 (Heaven) 的8个卦
(1, 1, '乾为天', 'Heaven over Heaven', 'Heaven', 'Heaven', 'Peak Performance State', 'Your energy is in a powerful creative phase. This is a time for bold action, leadership, and initiating what you''ve been planning.', 'Take the Lead — Step forward with confidence. Your vision is clear and the timing supports action.', 'Start What Matters — Begin that project, have that conversation, make that decision you''ve been postponing.', 'Maintain Integrity — Success comes from alignment with your core values, not just ambition.', 'NOW', 'Avoid arrogance. Power without humility creates resistance.', 'Career'),
(2, 44, '天风姤', 'Heaven over Wind', 'Heaven', 'Wind', 'Unexpected Opportunity', 'A surprising opportunity is emerging. This could be a chance meeting, an unexpected offer, or a sudden insight that changes your trajectory. Stay alert.', 'Stay Open — Be receptive to unexpected encounters. The best opportunities often come disguised as coincidences.', 'Act Quickly — This window may be brief. Trust your intuition and move before overthinking.', 'Evaluate Alignment — Not every opportunity serves your long-term vision. Check if it matches your core values.', 'NOW', 'Don''t let excitement override discernment. Haste makes waste.', 'Opportunity'),
(3, 14, '火天大有', 'Fire over Heaven', 'Fire', 'Heaven', 'Abundance Mindset', 'You are in a phase of harvest and abundance. Your efforts are bearing fruit, and resources are flowing toward you. This is your time to shine.', 'Receive Gracefully — Allow yourself to accept success without guilt or self-sabotage.', 'Share the Wealth — Generosity amplifies abundance. Support others on their journey.', 'Invest Wisely — Use this prosperous phase to build long-term security, not just short-term pleasure.', 'NOW', 'Success can breed complacency. Stay hungry, stay humble.', 'Wealth'),
(4, 34, '雷天大壮', 'Thunder over Heaven', 'Thunder', 'Heaven', 'Controlled Power', 'You have significant energy and momentum right now. This is powerful but potentially overwhelming. Channel this force strategically.', 'Direct Your Force — Energy without direction creates chaos. Focus on one major goal.', 'Pace Yourself — Sprinting is unsustainable. Build in recovery time.', 'Check Your Impact — Your power affects others. Lead with awareness.', 'ADJUST', 'Uncontrolled strength damages relationships and opportunities.', 'Leadership'),
(5, 5, '水天需', 'Water over Heaven', 'Water', 'Heaven', 'Strategic Patience', 'The timing isn''t quite right yet. Your role now is to prepare and position yourself for when the moment arrives.', 'Prepare Thoroughly — Use this time to build skills, resources, and relationships.', 'Stay Alert — Watch for signs that conditions are shifting.', 'Cultivate Patience — Forcing action now wastes energy and creates complications.', 'WAIT', 'Don''t confuse waiting with inaction. Preparation is active work.', 'Timing'),
(6, 26, '山天大畜', 'Mountain over Heaven', 'Mountain', 'Heaven', 'Resource Building', 'You are in an accumulation phase. This is about storing energy, knowledge, and resources for future use. Think long-term, not immediate gratification.', 'Build Your Reserve — Invest in skills, relationships, and assets that compound over time.', 'Delay Gratification — Say no to good opportunities to say yes to great ones later.', 'Protect Your Assets — What you''ve built needs guarding. Set boundaries.', 'WAIT', 'Hoarding without purpose creates stagnation. Know your why.', 'Wealth'),
(7, 11, '地天泰', 'Earth over Heaven', 'Earth', 'Heaven', 'Integration and Flow', 'Heaven and earth are in harmony. This is a rare state where your inner vision and outer reality align. Flow with this natural order.', 'Trust the Flow — When conditions align, don''t resist. Move with confidence.', 'Bridge Worlds — Connect your spiritual/intuitive side with practical action.', 'Maintain Balance — Success requires both vision (heaven) and grounding (earth).', 'NOW', 'Harmony can make you complacent. Stay engaged.', 'Harmony'),
(8, 43, '泽天夬', 'Lake over Heaven', 'Lake', 'Heaven', 'Decisive Breakthrough', 'A breakthrough is imminent. Something that has been blocked is about to release. This requires decisive action at the right moment.', 'Prepare for Release — The dam is about to break. Position yourself for the flow.', 'Act Decisively — When the moment comes, move without hesitation.', 'Manage the Aftermath — Breakthroughs create new challenges. Be ready.', 'NOW', 'Premature action wastes the breakthrough. Timing is everything.', 'Breakthrough'),

-- 上卦为兑 (Lake) 的8个卦
(9, 58, '兑为泽', 'Lake over Lake', 'Lake', 'Lake', 'Authentic Joy', 'You are in a phase of genuine happiness and connection. This joy is contagious and creates positive ripples in your relationships.', 'Celebrate Genuinely — Allow yourself to feel joy without guilt or fear of jinxing it.', 'Spread Positivity — Your energy uplifts others. Share your light generously.', 'Deepen Connections — Joy creates openings for intimacy. Have those meaningful conversations.', 'NOW', 'Don''t use happiness to avoid necessary difficult conversations.', 'Relationships'),
(10, 10, '天泽履', 'Heaven over Lake', 'Heaven', 'Lake', 'Conscious Action', 'You are walking a delicate path. Each step matters. This requires mindfulness, preparation, and respect for the terrain.', 'Step Mindfully — Rushing leads to missteps. Move with awareness and intention.', 'Respect Protocol — There are unwritten rules here. Observe before acting.', 'Build Credibility — Your reputation is your foundation. Guard it carefully.', 'ADJUST', 'Overconfidence on unstable ground leads to falls.', 'Career'),
(11, 38, '火泽睽', 'Fire over Lake', 'Fire', 'Lake', 'Navigating Difference', 'There is tension or misalignment in your environment. Opposing forces are at play. This requires diplomatic skill to navigate.', 'Find Common Ground — Beneath the surface disagreement, shared interests exist.', 'Respect Diversity — Different perspectives strengthen the whole. Don''t force uniformity.', 'Know When to Separate — Some paths must diverge. Graceful exits preserve relationships.', 'ADJUST', 'Forcing unity where there is natural divergence creates resentment.', 'Relationships'),
(12, 54, '雷泽归妹', 'Thunder over Lake', 'Thunder', 'Lake', 'Conscious Commitment', 'You are entering a new role or commitment. This brings excitement but also responsibility. Choose your obligations wisely.', 'Clarify Expectations — Misaligned expectations destroy relationships. Communicate clearly.', 'Honor Your Word — Commitments made lightly become heavy burdens. Think before promising.', 'Grow Into the Role — You may feel unprepared. That''s normal. Learn as you go.', 'ADJUST', 'Committing from pressure rather than choice leads to regret.', 'Relationships'),
(13, 61, '风泽中孚', 'Wind over Lake', 'Wind', 'Lake', 'Authentic Trust', 'This is a time for genuine connection and trust-building. Surface-level interactions won''t suffice. Go deep.', 'Lead with Vulnerability — Trust is built through shared openness, not perfect performance.', 'Keep Your Promises — Integrity is your most valuable currency. Spend it wisely.', 'Trust Your Intuition — Your gut knows who is trustworthy. Listen to it.', 'NOW', 'Blind trust is naive. Verify while you trust.', 'Relationships'),
(14, 60, '水泽节', 'Water over Lake', 'Water', 'Lake', 'Sustainable Rhythm', 'You need to establish healthy limits and rhythms. Too much or too little creates imbalance. Find your sustainable pace.', 'Set Clear Boundaries — Know your limits and communicate them. No is a complete sentence.', 'Create Rituals — Sustainable success requires consistent habits, not sporadic effort.', 'Moderate Extremes — Both excess and deprivation deplete you. Seek the middle way.', 'ADJUST', 'Rigidity in boundaries creates isolation. Stay flexible.', 'Wellness'),
(15, 41, '山泽损', 'Mountain over Lake', 'Mountain', 'Lake', 'Strategic Sacrifice', 'This phase requires letting go. Something must be released for something greater to emerge. Choose your sacrifices wisely.', 'Identify the Cost — Every gain has a price. Know what you''re paying.', 'Release with Grace — Letting go is hard. Do it with gratitude, not resentment.', 'Focus on Net Gain — Short-term loss for long-term gain is wisdom, not failure.', 'ADJUST', 'Sacrificing your core values is never worth any gain.', 'Growth'),
(16, 19, '地泽临', 'Earth over Lake', 'Earth', 'Lake', 'Approach with Awareness', 'You are drawing closer to something significant—a goal, a person, a new phase. This requires both courage and discernment.', 'Show Up Authentically — Approach from your true self, not a persona.', 'Observe Before Acting — Gather intelligence. Understand the landscape before committing.', 'Build Gradually — Deep connections and achievements require time. Don''t rush intimacy.', 'NOW', 'Approaching from neediness repels what you seek.', 'Relationships'),

-- 上卦为离 (Fire) 的8个卦
(17, 30, '离为火', 'Fire over Fire', 'Fire', 'Fire', 'Radiant Presence', 'Your inner light is strong right now. This is a time for visibility, clarity, and illuminating the path for yourself and others.', 'Shine Your Light — Don''t hide your gifts. The world needs your unique illumination.', 'Clarify Your Vision — Use this clarity to define what you truly want.', 'Inspire Others — Your enthusiasm is contagious. Lead by example.', 'NOW', 'Bright lights cast shadows. Be aware of what you illuminate.', 'Leadership'),
(18, 13, '天火同人', 'Heaven over Fire', 'Heaven', 'Fire', 'Tribal Alignment', 'You are finding your people. Shared vision and values create powerful bonds. This is community-building energy.', 'Find Your Tribe — Seek those who share your vision. Collaboration amplifies impact.', 'Align on Values — Surface agreement isn''t enough. Ensure core value alignment.', 'Contribute Generously — Community thrives on mutual giving. Be a net positive.', 'NOW', 'Groupthink kills innovation. Maintain independent thought.', 'Community'),
(19, 49, '泽火革', 'Lake over Fire', 'Lake', 'Fire', 'Conscious Transformation', 'Major change is necessary and inevitable. The old structure no longer serves. Embrace the transformation.', 'Release the Old — Clinging to what worked before blocks what comes next.', 'Lead the Change — Don''t wait for change to happen to you. Be the catalyst.', 'Communicate the Vision — Change creates fear. Paint a compelling picture of the future.', 'NOW', 'Change for change''s sake creates chaos. Know your destination.', 'Transformation'),
(20, 55, '雷火丰', 'Thunder over Fire', 'Thunder', 'Fire', 'Peak Experience', 'You are at a peak moment—abundance, success, and energy are at their height. Enjoy this, but prepare for the cycle.', 'Savor the Moment — Peak experiences are rare. Be fully present.', 'Document Your Success — Capture learnings while they''re fresh. You''ll need them later.', 'Prepare for Transition — Peaks are followed by valleys. Build your reserves.', 'NOW', 'Peaks create complacency. Stay alert for the descent.', 'Success'),
(21, 37, '风火家人', 'Wind over Fire', 'Wind', 'Fire', 'Foundation Building', 'Your focus shifts to home, family, and foundational relationships. This is about creating stability and nurturing your roots.', 'Invest in Relationships — Strong families and teams weather any storm.', 'Create Safe Space — Your environment shapes your energy. Make it supportive.', 'Honor Your Roots — Where you came from matters. Integrate your history.', 'NOW', 'Foundation first.', 'Family'),
(22, 63, '水火既济', 'Water over Fire', 'Water', 'Fire', 'Completion and Integration', 'A cycle is completing. Water and fire find balance. This is a moment of achievement and closure.', 'Acknowledge Completion — Take time to recognize what you''ve accomplished.', 'Integrate Learnings — Don''t rush to the next thing. Absorb the lessons.', 'Prepare for New Cycle — Completion is also beginning. Rest before the next launch.', 'NOW', 'Completion creates space.', 'Achievement'),
(23, 22, '山火贲', 'Mountain over Fire', 'Mountain', 'Fire', 'Authentic Presentation', 'This is about presentation and appearance, but grounded in substance. Beauty serves function, not the reverse.', 'Polish Your Presentation — Good work deserves good packaging. Invest in how you show up.', 'Maintain Substance — Style without substance is empty. Ensure depth beneath the beauty.', 'First Impressions Matter — People judge quickly. Make yours count.', 'ADJUST', 'Focusing on appearance neglects essence. Don''t lose yourself in the image.', 'Presentation'),
(24, 36, '地火明夷', 'Earth over Fire', 'Earth', 'Fire', 'Hidden Potential', 'Your light is temporarily obscured. This is a challenging phase, but your inner fire still burns. Protect it.', 'Protect Your Flame — In difficult times, guard your energy and optimism.', 'Work Behind the Scenes — Not all progress is visible. Trust the process.', 'Prepare for Return — This darkness is temporary. Position for the light''s return.', 'WAIT', 'Despair in dark times blinds you to emerging opportunities.', 'Resilience'),

-- 上卦为震 (Thunder) 的8个卦
(25, 51, '震为雷', 'Thunder over Thunder', 'Thunder', 'Thunder', 'Disruptive Awakening', 'A sudden shock or realization is jolting you awake. This disruption feels uncomfortable but is necessary for growth. The old complacency is breaking.', 'Embrace the Shake-up — Disruption clears space for transformation. Don''t resist the change.', 'Find Your Center — In chaos, your internal stability matters most. Ground yourself daily.', 'Act on Insights — The wake-up call came for a reason. Make the necessary changes now.', 'NOW', 'Panic leads to poor decisions. Stay centered in the storm.', 'Transformation'),
(26, 25, '天雷无妄', 'Heaven over Thunder', 'Heaven', 'Thunder', 'Effortless Action', 'Things are flowing naturally when you stop forcing. This is wu-wei in action—effortless effort. Trust the natural order.', 'Stop Forcing — The harder you push, the more resistance you create. Let go.', 'Align with Nature — Work with natural rhythms, not against them.', 'Trust the Process — When you''re in the flow, outcomes happen without struggle.', 'NOW', 'Effortless doesn''t mean passive. Stay engaged without attachment.', 'Flow'),
(27, 17, '泽雷随', 'Lake over Thunder', 'Lake', 'Thunder', 'Adaptive Following', 'This is a time to follow rather than lead. There''s wisdom in riding the momentum of forces greater than yourself.', 'Follow the Energy — Don''t swim upstream. Go where the current takes you.', 'Choose Your Leader — Be selective about what/who you follow. Alignment matters.', 'Stay Flexible — Conditions change quickly. Adaptability is your superpower.', 'ADJUST', 'Blind following leads off cliffs. Maintain discernment.', 'Strategy'),
(28, 21, '火雷噬嗑', 'Fire over Thunder', 'Fire', 'Thunder', 'Decisive Action', 'This situation requires clear decisions and firm execution. Hesitation creates more problems than wrong action.', 'Make the Call — Analysis paralysis kills progress. Decide and move.', 'Execute Completely — Half-measures fail. Commit fully to your decision.', 'Address Obstacles — Remove what''s blocking progress. Be direct.', 'NOW', 'Speed without direction creates chaos. Know your target.', 'Decision'),
(29, 42, '风雷益', 'Wind over Thunder', 'Wind', 'Thunder', 'Accelerated Growth', 'You are in a phase of rapid expansion and benefit. Small investments yield significant returns. Growth compounds quickly.', 'Invest in Growth — Put resources into what expands your capacity.', 'Share the Gains — Generosity in good times creates loyalty.', 'Build Systems — Rapid growth needs structure. Create scalable foundations.', 'NOW', 'Growth phase is here.', 'Growth'),
(30, 3, '水雷屯', 'Water over Thunder', 'Water', 'Thunder', 'Difficult Beginnings', 'You are at the beginning of something new. Energy is building but not yet flowing smoothly. Expect some resistance.', 'Start Small — Don''t try to do everything at once. Focus on the first step.', 'Build Foundations — Invest time in preparation and planning now.', 'Persist Through Difficulty — Initial challenges are normal; they test your commitment.', 'ADJUST', 'Don''t rush. Premature action wastes energy.', 'Beginnings'),
(31, 27, '山雷颐', 'Mountain over Thunder', 'Mountain', 'Thunder', 'Self-Nourishment', 'Your focus shifts to self-care and nourishment. This is about feeding yourself—body, mind, and spirit—before serving others.', 'Prioritize Self-Care — You cannot pour from an empty cup. Fill yourself first.', 'Choose Quality Inputs — What you consume shapes who you become. Be selective.', 'Establish Rituals — Sustainable nourishment requires consistent habits.', 'WAIT', 'Self-care can become self-indulgence. Maintain discipline.', 'Wellness'),
(32, 24, '地雷复', 'Earth over Thunder', 'Earth', 'Thunder', 'Cyclical Return', 'Something is returning—an opportunity, a relationship, a pattern. This is the natural cycle of endings and beginnings.', 'Welcome the Return — What comes back may be exactly what you need now.', 'Learn from the Past — This time, apply the lessons from before.', 'Start Fresh — Returns are new beginnings. Don''t carry old baggage.', 'NOW', 'The cycle turns.', 'Cycles'),

-- 上卦为巽 (Wind) 的8个卦
(33, 57, '巽为风', 'Wind over Wind', 'Wind', 'Wind', 'Gentle Persistence', 'Progress is happening gradually, like wind shaping stone. This is slow but steady transformation. Patience pays off.', 'Keep Showing Up — Consistency beats intensity. Small daily actions compound.', 'Adapt Your Approach — Wind finds a way around obstacles. Be flexible.', 'Trust Subtle Power — Gentle persistence achieves what force cannot.', 'ADJUST', 'Impatience makes you abandon progress just before breakthrough.', 'Persistence'),
(34, 44, '天风姤', 'Heaven over Wind', 'Heaven', 'Wind', 'Unexpected Encounter', 'A surprising opportunity is emerging. This could be a chance meeting, an unexpected offer, or a sudden insight that changes your trajectory. Stay alert.', 'Stay Open — Be receptive to unexpected encounters. The best opportunities often come disguised as coincidences.', 'Act Quickly — This window may be brief. Trust your intuition and move before overthinking.', 'Evaluate Alignment — Not every opportunity serves your long-term vision. Check if it matches your core values.', 'NOW', 'Don''t let excitement override discernment. Haste makes waste.', 'Opportunity'),
(35, 28, '泽风大过', 'Lake over Wind', 'Lake', 'Wind', 'Managing Excess', 'Something is out of balance—too much or too little. This extreme creates stress and potential breakdown.', 'Identify the Imbalance — What''s excessive or deficient? Name it clearly.', 'Reduce the Load — You may be carrying too much. Delegate or release.', 'Reinforce Structures — Under stress, your foundations need attention.', 'ADJUST', 'Ignoring imbalance leads to collapse. Address it now.', 'Balance'),
(36, 50, '火风鼎', 'Fire over Wind', 'Fire', 'Wind', 'Transformation and Renewal', 'You are in a phase of profound transformation. Old structures are being reshaped into something new and more valuable.', 'Embrace the Refining Fire — Heat transforms raw material into something stronger.', 'Release the Old Form — What you were must die for what you''ll become.', 'Shape the New — You have agency in this transformation. Design intentionally.', 'NOW', 'Transformation is underway.', 'Transformation'),
(37, 32, '雷风恒', 'Thunder over Wind', 'Thunder', 'Wind', 'Sustainable Commitment', 'This is about long-term consistency. Not dramatic breakthroughs, but steady persistence over time.', 'Commit for the Long Term — Quick wins are seductive but fleeting. Think decades.', 'Adapt While Persisting — Constancy doesn''t mean rigidity. Adjust tactics, not vision.', 'Celebrate Milestones — Long journeys need markers. Acknowledge progress.', 'NOW', 'Persistence pays.', 'Commitment'),
(38, 48, '水风井', 'Water over Wind', 'Water', 'Wind', 'Source Connection', 'You need to reconnect with your source—your values, your community, your inner wellspring. This is about sustainable nourishment.', 'Return to Source — What originally nourished you? Reconnect there.', 'Maintain the Well — Resources need care. Don''t deplete without replenishing.', 'Share the Water — Abundant sources should serve the community.', 'WAIT', 'Replenish before you give.', 'Sustainability'),
(39, 18, '山风蛊', 'Mountain over Wind', 'Mountain', 'Wind', 'Decay and Renewal', 'Something has gone stale or corrupt. This decay is uncomfortable but necessary—it creates space for renewal.', 'Acknowledge the Decay — Denial prolongs suffering. Name what''s not working.', 'Root Out Corruption — Surface fixes won''t work. Go to the source.', 'Rebuild with Wisdom — Use the lessons from failure to build stronger.', 'ADJUST', 'Hasty repairs create future problems. Do it right.', 'Renewal'),
(40, 20, '地风升', 'Earth over Wind', 'Earth', 'Wind', 'Steady Ascent', 'You are in a phase of natural growth and elevation. Like a plant growing toward light, progress feels organic.', 'Grow Toward the Light — Orient toward what nourishes and elevates you.', 'Root Deeply — Sustainable growth needs strong foundations.', 'Trust Natural Timing — Forced growth is weak. Let it happen organically.', 'NOW', 'Growth is natural.', 'Growth'),

-- 上卦为坎 (Water) 的8个卦
(41, 29, '坎为水', 'Water over Water', 'Water', 'Water', 'Navigating Danger', 'You are in deep waters. This is risky but also rich with potential. Courage and caution must balance.', 'Stay Calm — Panic in danger creates more danger. Breathe and assess.', 'Find the Current — Water has flow. Work with it, not against it.', 'Trust Your Training — You''ve prepared for this. Let your skills guide you.', 'ADJUST', 'Recklessness in danger is fatal. Respect the risk.', 'Risk'),
(42, 6, '天水讼', 'Heaven over Water', 'Heaven', 'Water', 'Conflict and Resolution', 'There is tension or conflict in the situation. Direct confrontation may not be the best path.', 'Seek Middle Ground — Look for solutions that address core needs of all parties.', 'Choose Battles Wisely — Not every disagreement needs to be resolved now.', 'Focus on Interests, Not Positions — Understand what people really need, not just what they say.', 'ADJUST', 'Winning an argument can mean losing a relationship. Choose wisely.', 'Conflict'),
(43, 47, '泽水困', 'Lake over Water', 'Lake', 'Water', 'Navigating Constraint', 'You feel trapped or constrained. Resources are limited, options seem few. This tests your creativity and resilience.', 'Accept the Constraint — Fighting reality wastes energy. Work within limits.', 'Find Creative Solutions — Limitation breeds innovation. Think differently.', 'Conserve Resources — This is temporary. Don''t deplete what you have.', 'WAIT', 'Despair in difficulty blinds you to emerging solutions.', 'Constraint'),
(44, 64, '火水未济', 'Fire over Water', 'Fire', 'Water', 'Unfinished Potential', 'You are at the beginning of a new cycle. Things are incomplete, but that''s the point—potential lives in the unfinished.', 'Embrace Incompleteness — You don''t need to have it all figured out. Start anyway.', 'Focus on Direction — Clarity emerges through action, not before.', 'Trust the Process — Completion will come. Be patient with the journey.', 'NOW', 'Begin before you''re ready.', 'Potential'),
(45, 40, '雷水解', 'Thunder over Water', 'Thunder', 'Water', 'Liberation and Relief', 'A difficult situation is resolving. Tension is releasing, obstacles are clearing. Relief is coming.', 'Let Go — Release your grip on what was. The struggle is ending.', 'Integrate the Lesson — What did this difficulty teach you? Capture it.', 'Move Forward Lightly — Don''t carry the weight forward. Travel light.', 'NOW', 'Release and move on.', 'Relief'),
(46, 59, '风水涣', 'Wind over Water', 'Wind', 'Water', 'Managing Dispersion', 'Things are scattering—attention, resources, energy. This dispersion can be creative or destructive, depending on how you manage it.', 'Focus the Scatter — Channel dispersed energy toward specific goals.', 'Let Go of the Unessential — Some dispersion is healthy. Release what doesn''t serve.', 'Gather What Matters — Protect what''s essential amid the scattering.', 'ADJUST', 'Total dispersion leaves you with nothing. Maintain a center.', 'Focus'),
(47, 4, '山水蒙', 'Mountain over Water', 'Mountain', 'Water', 'Learning and Innocence', 'You are in a learning phase. What you need to know will be revealed through experience, not just study.', 'Stay Curious — Approach the situation as a student, even if you''re experienced.', 'Seek Guidance — A mentor or teacher can accelerate your learning.', 'Learn by Doing — Theory isn''t enough; take small actions to test and learn.', 'WAIT', 'Don''t pretend to know what you don''t. Humility accelerates growth.', 'Learning'),
(48, 7, '地水师', 'Earth over Water', 'Earth', 'Water', 'Team and Organization', 'This situation requires coordinated effort. Your role may be to lead, follow, or facilitate collaboration.', 'Clarify Roles — Make sure everyone understands their part and how it contributes to the whole.', 'Build Trust — Team success depends on mutual confidence and clear communication.', 'Lead by Example — Your actions set the standard for others.', 'NOW', 'Collective energy supports action.', 'Teamwork'),

-- 上卦为艮 (Mountain) 的8个卦
(49, 52, '艮为山', 'Mountain over Mountain', 'Mountain', 'Mountain', 'Conscious Stillness', 'This is a time for stopping. Not passive inaction, but conscious pause. The mountain doesn''t move—it doesn''t need to.', 'Stop Completely — Half-stopping isn''t stopping. Full pause allows clarity.', 'Observe from Stillness — What do you see when you''re not moving?', 'Wait for the Signal — Don''t resume until you have clear direction.', 'WAIT', 'Permanent stillness becomes stagnation. Know when to move again.', 'Stillness'),
(50, 33, '天山遁', 'Heaven over Mountain', 'Heaven', 'Mountain', 'Strategic Withdrawal', 'Retreat is the wise move now. This isn''t defeat—it''s preserving energy for better timing.', 'Step Back Gracefully — Retreat with dignity, not desperation.', 'Preserve Your Energy — Live to fight another day. Don''t waste resources.', 'Prepare for Return — Use this time to gather strength and intelligence.', 'WAIT', 'Shame about retreat prevents necessary withdrawal.', 'Strategy'),
(51, 31, '泽山咸', 'Lake over Mountain', 'Lake', 'Mountain', 'Mutual Attraction', 'There is natural chemistry and resonance here. This attraction can be romantic, professional, or creative.', 'Follow the Attraction — Chemistry is information. Pay attention to what draws you.', 'Check Reciprocity — Attraction works best when mutual. Ensure alignment.', 'Build on Resonance — Shared energy creates momentum. Move together.', 'NOW', 'Chemistry is present.', 'Attraction'),
(52, 56, '火山旅', 'Fire over Mountain', 'Fire', 'Mountain', 'Journey and Exploration', 'You are in a phase of movement and exploration. This may be physical travel or metaphorical journey into new territory.', 'Travel Light — Baggage slows you down. Bring only what''s essential.', 'Stay Present — The journey is the destination. Don''t rush to arrive.', 'Gather Wisdom — Every place teaches something. Stay curious.', 'NOW', 'Movement serves you.', 'Journey'),
(53, 62, '雷山小过', 'Thunder over Mountain', 'Thunder', 'Mountain', 'Small Excess and Caution', 'Minor excesses and small mistakes are likely. This is a time for caution with details, not major risks.', 'Mind the Details — Small oversights create big problems now.', 'Avoid Major Risks — This isn''t the time for bold gambles. Play it safe.', 'Correct Quickly — Small errors are easy to fix if caught early.', 'ADJUST', 'Ignoring small problems makes them big.', 'Caution'),
(54, 53, '风山渐', 'Wind over Mountain', 'Wind', 'Mountain', 'Gradual Progress', 'Progress is happening step by step. Like a tree growing, change is almost imperceptible but real.', 'Trust the Process — You may not see daily progress, but it''s happening.', 'Build Step by Step — Each small action adds to the foundation.', 'Celebrate Small Wins — Progress is progress, no matter the size.', 'NOW', 'Gradual progress is real progress.', 'Progress'),
(55, 39, '水山蹇', 'Water over Mountain', 'Water', 'Mountain', 'Navigating Obstacles', 'The path is difficult. Obstacles are real and significant. This tests your persistence and creativity.', 'Accept the Difficulty — Denial wastes energy. This is hard, and that''s okay.', 'Find Another Way — When the direct path is blocked, explore alternatives.', 'Ask for Help — Difficult journeys need companions. Don''t go alone.', 'WAIT', 'Stubborn persistence in impossible conditions is foolish.', 'Obstacles'),
(56, 15, '地山谦', 'Earth over Mountain', 'Earth', 'Mountain', 'Humble Power', 'True strength doesn''t need to show off. This is about quiet confidence and modest leadership.', 'Let Results Speak — Don''t boast. Your work will prove your worth.', 'Acknowledge Others — Share credit generously. It amplifies your influence.', 'Stay Grounded — Success doesn''t make you superior. Stay humble.', 'NOW', 'Humility serves you.', 'Humility'),

-- 上卦为坤 (Earth) 的8个卦
(57, 2, '坤为地', 'Earth over Earth', 'Earth', 'Earth', 'Receptive Power', 'You are in a receptive, nurturing phase. This is not a time for forcing outcomes, but for allowing things to unfold naturally.', 'Practice Receptivity — Open yourself to support, ideas, and opportunities that come to you.', 'Nurture What Exists — Focus on caring for current projects and relationships rather than starting new ones.', 'Trust the Process — Results may not be visible yet, but groundwork is being laid.', 'WAIT', 'Don''t mistake passivity for receptivity. Stay engaged while allowing.', 'Receptivity'),
(58, 12, '天地否', 'Heaven over Earth', 'Heaven', 'Earth', 'Disconnection and Blockage', 'Heaven and earth are not communicating. There''s a blockage between vision and reality, between you and others.', 'Acknowledge the Block — Denial doesn''t help. Name the disconnection.', 'Don''t Force Connection — Pushing against blockage creates more resistance.', 'Wait for Natural Opening — Blocks clear on their own timing. Be patient.', 'WAIT', 'Forcing connection damages relationships.', 'Blockage'),
(59, 45, '泽地萃', 'Lake over Earth', 'Lake', 'Earth', 'Gathering and Assembly', 'This is a time for bringing people or resources together. Collective energy creates what individuals cannot.', 'Call People Together — Convene the tribe. Shared purpose unites.', 'Create Container — Gatherings need structure. Design intentional space.', 'Honor Contributions — Everyone brings something valuable. Acknowledge all.', 'NOW', 'Gathering serves the goal.', 'Community'),
(60, 35, '火地晋', 'Fire over Earth', 'Fire', 'Earth', 'Advancement and Recognition', 'You are rising. Recognition is coming, position is improving. This is your time to advance.', 'Step Into the Light — Don''t hide your achievements. Let them be seen.', 'Prepare for More Responsibility — Advancement brings new demands. Get ready.', 'Help Others Rise — Bring people with you. Shared success lasts.', 'NOW', 'Advancement is happening.', 'Advancement'),
(61, 16, '雷地豫', 'Thunder over Earth', 'Thunder', 'Earth', 'Enthusiastic Preparation', 'There''s excitement and positive energy. This enthusiasm is fuel, but it needs direction.', 'Channel the Energy — Enthusiasm without direction is just noise. Focus it.', 'Prepare Thoroughly — Excitement makes you want to jump in. Prepare first.', 'Share the Joy — Positive energy is contagious. Spread it generously.', 'NOW', 'Enthusiasm serves action.', 'Enthusiasm'),
(62, 46, '地风升', 'Earth over Wind', 'Earth', 'Wind', 'Steady Ascent', 'You are in a phase of natural growth and elevation. Like a plant growing toward light, progress feels organic.', 'Grow Toward the Light — Orient toward what nourishes and elevates you.', 'Root Deeply — Sustainable growth needs strong foundations.', 'Trust Natural Timing — Forced growth is weak. Let it happen organically.', 'NOW', 'Growth is natural.', 'Growth'),
(63, 8, '水地比', 'Water over Earth', 'Water', 'Earth', 'Alliance and Support', 'This is a favorable time for building alliances, partnerships, and close connections.', 'Reach Out — Initiate contact with people who share your values and goals.', 'Offer Support First — Generosity creates reciprocity.', 'Choose Allies Carefully — Quality of connection matters more than quantity.', 'NOW', 'Relationship energy is favorable.', 'Alliance'),
(64, 23, '山地剥', 'Mountain over Earth', 'Mountain', 'Earth', 'Decline and Release', 'Something is falling away. This decline feels like loss, but it''s clearing space for the new.', 'Let It Fall — Don''t try to hold up what''s naturally declining.', 'Protect the Core — While outer layers peel away, guard what''s essential.', 'Prepare for Renewal — After decline comes rebirth. Position for it.', 'WAIT', 'Clinging to what''s ending prevents what''s beginning.', 'Release');

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_hexagrams_timing ON hexagrams_64(timing_advice);
CREATE INDEX IF NOT EXISTS idx_hexagrams_category ON hexagrams_64(category);
CREATE INDEX IF NOT EXISTS idx_hexagrams_upper ON hexagrams_64(upper_trigram);
CREATE INDEX IF NOT EXISTS idx_hexagrams_lower ON hexagrams_64(lower_trigram);

-- 验证数据
SELECT COUNT(*) as total_hexagrams FROM hexagrams_64;
